# -*- coding: utf-8 -*-
"""Zadaca_bez_modula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpg0pF5V3yg4nnX5DzstWMM0Wh5YUqXG
"""

def kvadriraj(x):
    return x ** 2

kvadriraj_lambda = lambda x: x ** 2

def zbroji_pa_kvadriraj(a, b):
    return (a + b) ** 2

zbroji_pa_kvadriraj_lambda = lambda a, b: (a + b) ** 2

def kvadriraj_duljinu(niz):
    return len(niz) ** 2

kvadriraj_duljinu_lambda = lambda niz: len(niz) ** 2

def pomnozi_i_potenciraj(x, y):
    return (y * 5) ** x

pomnozi_i_potenciraj_lambda = lambda x, y: (y * 5) ** x

def paran_broj(x):
    if x % 2 == 0:
        return True
    else:
        return None

paran_broj_lambda = lambda x: True if x % 2 == 0 else None

print(kvadriraj(4))
print(kvadriraj_lambda(4))

print(zbroji_pa_kvadriraj(2, 3))
print(zbroji_pa_kvadriraj_lambda(2, 3))

print(kvadriraj_duljinu([1,2,3,4]))
print(kvadriraj_duljinu_lambda([1,2,3,4]))

print(pomnozi_i_potenciraj(3, 2))
print(pomnozi_i_potenciraj_lambda(3, 2))

print(paran_broj(6))
print(paran_broj_lambda(6))

nizovi = ["jabuka", "kruška", "banana", "naranča"]
kvadrirane_duljine = list(map(lambda s: len(s) ** 2, nizovi))
print(kvadrirane_duljine)

brojevi = [1, 21, 33, 45, 2, 2, 1, -32, 9, 10]
veci_od_5 = list(filter(lambda x: x > 5, brojevi))
print(veci_od_5)

brojevi = [10, 5, 12, 15, 20]
transform = dict(map(lambda x: (x, x**2), brojevi))
print(transform)

studenti = [
    {"ime": "Ivan", "prezime": "Ivić", "godine": 19},
    {"ime": "Marko", "prezime": "Marković", "godine": 22},
    {"ime": "Ana", "prezime": "Anić", "godine": 21},
    {"ime": "Petra", "prezime": "Petrić", "godine": 13},
    {"ime": "Iva", "prezime": "Ivić", "godine": 17},
    {"ime": "Mate", "prezime": "Matić", "godine": 18}
]
svi_punoljetni = all(map(lambda s: s["godine"] >= 18, studenti))
print(svi_punoljetni)

rijeci = ["jabuka", "pas", "knjiga", "zvijezda", "prijatelj", "zvuk", "čokolada", "ples",
"pjesma", "otorinolaringolog"]
min_duljina = int(input("Unesite minimalnu duljinu riječi: "))
duge_rijeci = list(filter(lambda r: len(r) > min_duljina, rijeci))
print(duge_rijeci)

parni_kvadrati = [x**2 for x in range(20, 51) if x % 2 == 0]
print(parni_kvadrati)

rijeci = ["jabuka", "pas", "knjiga", "zvijezda", "prijatelj", "zvuk", "čokolada", "ples",
"pjesma", "otorinolaringolog"]
duljine_sa_slovom_a = [len(r) for r in rijeci if 'a' in r]
print(duljine_sa_slovom_a)

kubovi = [{x: x**3 if x % 2 != 0 else x} for x in range(1, 11)]
print(kubovi)

korijeni = {x: round(x**0.5, 2) for x in range(50, 501, 50)}
print(korijeni)

studenti = [
{"ime": "Ivan", "prezime": "Ivić", "bodovi": [12, 23, 53, 64]},
{"ime": "Marko", "prezime": "Marković", "bodovi": [33, 15, 34, 45]},
{"ime": "Ana", "prezime": "Anić", "bodovi": [8, 9, 4, 23, 11]},
{"ime": "Petra", "prezime": "Petrić", "bodovi": [87, 56, 77, 44, 98]},
{"ime": "Iva", "prezime": "Ivić", "bodovi": [23, 45, 67, 89, 12]},
{"ime": "Mate", "prezime": "Matić", "bodovi": [75, 34, 56, 78, 23]}
]
zbrojeni_bodovi = [{s["prezime"]: sum(s["bodovi"])} for s in studenti]
print(zbrojeni_bodovi)

import math
faktorijeli = {x: [math.factorial(i) for i in range(1, x+1)] for x in range(1, 11)}
print(faktorijeli)

# JOŠ KLASE, OBJEKTI, MODULI, PAKETI

from datetime import datetime

class Automobil:
    def __init__(self, marka, model, godina_proizvodnje, kilometraza):
        self.marka = marka
        self.model = model
        self.godina_proizvodnje = godina_proizvodnje
        self.kilometraza = kilometraza

    def ispis(self):
        print(f"Marka: {self.marka}")
        print(f"Model: {self.model}")
        print(f"Godina proizvodnje: {self.godina_proizvodnje}")
        print(f"Kilometraža: {self.kilometraza} km")

    def starost(self):
        trenutna_godina = datetime.now().year
        star = trenutna_godina - self.godina_proizvodnje
        print(f"Automobil je star {star} lit.")


auto = Automobil("Yugo", "45", 1968, 450000)

auto.ispis()
auto.starost()

import math

class Kalkulator:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def zbroj(self):
        return self.a + self.b

    def oduzimanje(self):
        return self.a - self.b

    def mnozenje(self):
        return self.a * self.b

    def dijeljenje(self):
        if self.b == 0:
            return "Ne moreš dijelit z nulon trubilo."
        return self.a / self.b

    def potenciranje(self):
        return self.a ** self.b

    def korijen(self):
        if self.a < 0:
            return "Ne moreš korijenovat negativan broj trubilo."
        return math.sqrt(self.a)


k = Kalkulator(9, 0)

print(k.zbroj())
print(k.oduzimanje())
print(k.mnozenje())
print(k.dijeljenje())
print(k.potenciranje())
print(k.korijen())

class Student:
    def __init__(self, ime, prezime, godine, ocjene):
        self.ime = ime
        self.prezime = prezime
        self.godine = godine
        self.ocjene = ocjene

    def prosjek(self):
        return sum(self.ocjene) / len(self.ocjene)


studenti = [
    {"ime": "Pero", "prezime": "Perić", "godine": 19, "ocjene": [5, 4, 3, 5, 2]},
    {"ime": "Elio", "prezime": "Pisak", "godine": 22, "ocjene": [3, 4, 5, 2, 3]},
    {"ime": "Aldo", "prezime": "Lakošeljac", "godine": 21, "ocjene": [5, 5, 5, 5, 5]},
    {"ime": "Marčelo", "prezime": "Lukež", "godine": 13, "ocjene": [2, 3, 2, 4, 3]},
    {"ime": "Pino", "prezime": "Kajin", "godine": 17, "ocjene": [4, 4, 4, 3, 5]},
    {"ime": "Marko", "prezime": "Matić", "godine": 18, "ocjene": [1, 3, 5, 5, 5]}
]

studenti_objekti = [Student(s["ime"], s["prezime"], s["godine"], s["ocjene"]) for s in studenti]

najbolji_student = max(studenti_objekti, key=lambda s: s.prosjek())

print(najbolji_student.ime, najbolji_student.prezime, najbolji_student.prosjek())

import math

class Krug:
    def __init__(self, r):
        self.r = r

    def opseg(self):
        return 2 * math.pi * self.r

    def povrsina(self):
        return math.pi * (self.r ** 2)


k = Krug(5)

print("Opseg:", k.opseg())
print("Površina:", k.povrsina())

class Radnik:
    def __init__(self, ime, pozicija, placa):
        self.ime = ime
        self.pozicija = pozicija
        self.placa = placa

    def work(self):
        print(f"Radim na poziciji {self.pozicija}")

class Manager(Radnik):
    def __init__(self, ime, pozicija, placa, department):
        super().__init__(ime, pozicija, placa)
        self.department = department

    def work(self):
        print(f"Radim na poziciji {self.pozicija} u odjelu {self.department}")

    def give_raise(self, radnik, povecanje):
        radnik.placa += povecanje
        print(f"{radnik.ime} sada ima plaću {radnik.placa}.")

drzavni_sluzbenik = Radnik("Damir Kajin", "Gradonacelnik Buzeta", 8000)
drzavni_sluzbenik_zesci = Manager("Andrej Plenki", "Premijer", 12000, "Prodavač magle")

drzavni_sluzbenik.work()
drzavni_sluzbenik_zesci.work()

# Sam sebi je diga plaću
drzavni_sluzbenik_zesci.give_raise(drzavni_sluzbenik_zesci, 2000)
