# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpg0pF5V3yg4nnX5DzstWMM0Wh5YUqXG
"""

def kvadriraj(x):
    return x ** 2

kvadriraj_lambda = lambda x: x ** 2

def zbroji_pa_kvadriraj(a, b):
    return (a + b) ** 2

zbroji_pa_kvadriraj_lambda = lambda a, b: (a + b) ** 2

def kvadriraj_duljinu(niz):
    return len(niz) ** 2

kvadriraj_duljinu_lambda = lambda niz: len(niz) ** 2

def pomnozi_i_potenciraj(x, y):
    return (y * 5) ** x

pomnozi_i_potenciraj_lambda = lambda x, y: (y * 5) ** x

def paran_broj(x):
    if x % 2 == 0:
        return True
    else:
        return None

paran_broj_lambda = lambda x: True if x % 2 == 0 else None

print(kvadriraj(4))
print(kvadriraj_lambda(4))

print(zbroji_pa_kvadriraj(2, 3))
print(zbroji_pa_kvadriraj_lambda(2, 3))

print(kvadriraj_duljinu([1,2,3,4]))
print(kvadriraj_duljinu_lambda([1,2,3,4]))

print(pomnozi_i_potenciraj(3, 2))
print(pomnozi_i_potenciraj_lambda(3, 2))

print(paran_broj(6))
print(paran_broj_lambda(6))

nizovi = ["jabuka", "kruška", "banana", "naranča"]
kvadrirane_duljine = list(map(lambda s: len(s) ** 2, nizovi))
print(kvadrirane_duljine)

brojevi = [1, 21, 33, 45, 2, 2, 1, -32, 9, 10]
veci_od_5 = list(filter(lambda x: x > 5, brojevi))
print(veci_od_5)

brojevi = [10, 5, 12, 15, 20]
transform = dict(map(lambda x: (x, x**2), brojevi))
print(transform)

studenti = [
    {"ime": "Ivan", "prezime": "Ivić", "godine": 19},
    {"ime": "Marko", "prezime": "Marković", "godine": 22},
    {"ime": "Ana", "prezime": "Anić", "godine": 21},
    {"ime": "Petra", "prezime": "Petrić", "godine": 13},
    {"ime": "Iva", "prezime": "Ivić", "godine": 17},
    {"ime": "Mate", "prezime": "Matić", "godine": 18}
]
svi_punoljetni = all(map(lambda s: s["godine"] >= 18, studenti))
print(svi_punoljetni)

rijeci = ["jabuka", "pas", "knjiga", "zvijezda", "prijatelj", "zvuk", "čokolada", "ples",
"pjesma", "otorinolaringolog"]
min_duljina = int(input("Unesite minimalnu duljinu riječi: "))
duge_rijeci = list(filter(lambda r: len(r) > min_duljina, rijeci))
print(duge_rijeci)

parni_kvadrati = [x**2 for x in range(20, 51) if x % 2 == 0]
print(parni_kvadrati)

rijeci = ["jabuka", "pas", "knjiga", "zvijezda", "prijatelj", "zvuk", "čokolada", "ples",
"pjesma", "otorinolaringolog"]
duljine_sa_slovom_a = [len(r) for r in rijeci if 'a' in r]
print(duljine_sa_slovom_a)

kubovi = [{x: x**3 if x % 2 != 0 else x} for x in range(1, 11)]
print(kubovi)

korijeni = {x: round(x**0.5, 2) for x in range(50, 501, 50)}
print(korijeni)

studenti = [
{"ime": "Ivan", "prezime": "Ivić", "bodovi": [12, 23, 53, 64]},
{"ime": "Marko", "prezime": "Marković", "bodovi": [33, 15, 34, 45]},
{"ime": "Ana", "prezime": "Anić", "bodovi": [8, 9, 4, 23, 11]},
{"ime": "Petra", "prezime": "Petrić", "bodovi": [87, 56, 77, 44, 98]},
{"ime": "Iva", "prezime": "Ivić", "bodovi": [23, 45, 67, 89, 12]},
{"ime": "Mate", "prezime": "Matić", "bodovi": [75, 34, 56, 78, 23]}
]
zbrojeni_bodovi = [{s["prezime"]: sum(s["bodovi"])} for s in studenti]
print(zbrojeni_bodovi)

import math
faktorijeli = {x: [math.factorial(i) for i in range(1, x+1)] for x in range(1, 11)}
print(faktorijeli)

# JOŠ KLASE, OBJEKTI, MODULI, PAKETI
